########################################################################
# Copyright (c) 1988-2012 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 10/13/2012
#
# Gcc Makefile for Xos libXosCore Static and Shared Library
########################################################################

#
# libXosCore C++ .cpp sources
#
libXosCore_CPP_SOURCES = \
$(PKG)/$(SRC)/xos/base/Platform.cpp \
$(PKG)/$(SRC)/xos/base/Error.cpp \
$(PKG)/$(SRC)/xos/base/Base.cpp \
$(PKG)/$(SRC)/xos/base/ExportBase.cpp \
$(PKG)/$(SRC)/xos/base/InterfaceBase.cpp \
$(PKG)/$(SRC)/xos/base/Array.cpp \
$(PKG)/$(SRC)/xos/base/Reference.cpp \
$(PKG)/$(SRC)/xos/base/Join.cpp \
$(PKG)/$(SRC)/xos/base/Wait.cpp \
$(PKG)/$(SRC)/xos/base/Acquired.cpp \
$(PKG)/$(SRC)/xos/base/Attached.cpp \
$(PKG)/$(SRC)/xos/base/Wrapped.cpp \
$(PKG)/$(SRC)/xos/base/Created.cpp \
$(PKG)/$(SRC)/xos/base/Opened.cpp \
$(PKG)/$(SRC)/xos/base/Locked.cpp \
$(PKG)/$(SRC)/xos/base/Locker.cpp \
$(PKG)/$(SRC)/xos/base/Stream.cpp \
$(PKG)/$(SRC)/xos/base/String.cpp \
$(PKG)/$(SRC)/xos/os/FILEStream.cpp \
$(PKG)/$(SRC)/xos/os/Logger.cpp \
$(PKG)/$(SRC)/xos/os/Main.cpp \
$(PKG)/$(SRC)/xos/os/MainBase.cpp \
$(PKG)/$(SRC)/xos/os/MainOpt.cpp \
$(PKG)/$(SRC)/xos/os/StreamLogger.cpp \
$(PKG)/$(SRC)/xos/os/os/Os.cpp \
$(PKG)/$(SRC)/xos/os/os/Mutexes.cpp \
$(PKG)/$(SRC)/xos/os/os/Semaphores.cpp \
$(PKG)/$(SRC)/xos/os/os/Threads.cpp \
$(PKG)/$(SRC)/xos/os/os/Processes.cpp \
$(PKG)/$(SRC)/xos/os/os/Times.cpp \
$(PKG)/$(SRC)/xos/fs/Path.cpp \
$(PKG)/$(SRC)/xos/fs/PathDirectory.cpp \
$(PKG)/$(SRC)/xos/fs/PathDirectoryAppender.cpp \
$(PKG)/$(SRC)/xos/fs/PathParser.cpp \
$(PKG)/$(SRC)/xos/fs/PathParserEvents.cpp \
$(PKG)/$(SRC)/xos/fs/Time.cpp \
$(PKG)/$(SRC)/xos/fs/os/Directory.cpp \
$(PKG)/$(SRC)/xos/fs/os/Entry.cpp \
$(PKG)/$(SRC)/xos/network/Addresses.cpp \
$(PKG)/$(SRC)/xos/network/Endpoints.cpp \
$(PKG)/$(SRC)/xos/network/Transports.cpp \
$(PKG)/$(SRC)/xos/network/os/Sockets.cpp \

#
# libXosCore Static Library C++ .cpp sources
#
_libXosCore_LIB_CPP_SOURCES = \
$(libXosCore_CPP_SOURCES) \

#
# libXosCore Shared Library C++ .cpp sources
#
_libXosCore_SLIB_CPP_SOURCES = \
$(libXosCore_CPP_SOURCES) \

