///////////////////////////////////////////////////////////////////////
/// Copyright (c) 1988-2015 $organization$
///
/// This software is provided by the author and contributors ``as is'' 
/// and any express or implied warranties, including, but not limited to, 
/// the implied warranties of merchantability and fitness for a particular 
/// purpose are disclaimed. In no event shall the author or contributors 
/// be liable for any direct, indirect, incidental, special, exemplary, 
/// or consequential damages (including, but not limited to, procurement 
/// of substitute goods or services; loss of use, data, or profits; or 
/// business interruption) however caused and on any theory of liability, 
/// whether in contract, strict liability, or tort (including negligence 
/// or otherwise) arising in any way out of the use of this software, 
/// even if advised of the possibility of such damage.
///
///   File: MainOpt.hpp
///
/// Author: $author$
///   Date: 4/24/2015
///////////////////////////////////////////////////////////////////////
#ifndef _XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAINOPT_HPP
#define _XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAINOPT_HPP

#include "xos/os/Main.hpp"

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPT "generate-prime"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTARG "number"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTUSE "Number of bits"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTVAL_S "p:"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTVAL_C 'p'
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTION \
   {XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTARG_RESULT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTVAL_C}, \

#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPT "use-bignum"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTARG ""
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTUSE ""
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTVAL_S "b"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTVAL_C 'b'
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTION \
   {XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTARG_RESULT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTVAL_C}, \

#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPT "use-mpint"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTARG ""
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTUSE ""
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTVAL_S "m"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTVAL_C 'm'
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTION \
   {XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTARG_RESULT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTVAL_C}, \

#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPT "random-seed"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTARG "number"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTUSE "Pseudo random seed"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTVAL_S "s:"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTVAL_C 's'
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTION \
   {XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTARG_RESULT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTVAL_C}, \

#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPT "generate-key"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTARG "number"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTUSE "Modulus bits"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTVAL_S "k:"
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTVAL_C 'k'
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTION \
   {XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTARG_RESULT, \
    XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTVAL_C}, \

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_OPTIONS_CHARS \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTVAL_S \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTVAL_S \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTVAL_S \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTVAL_S \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTVAL_S \
   XOS_MAIN_OPTIONS_CHARS

#define XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_OPTIONS_OPTIONS \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATE_OPTION \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_GENERATEPRIME_OPTION \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_BIGNUM_OPTION \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_MPINT_OPTION \
   XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAIN_RANDOMSEED_OPTION \
   XOS_MAIN_OPTIONS_OPTIONS

namespace xos {
namespace app {
namespace console {
namespace crypto {
namespace rsa {
namespace generator {

} // namespace generator 
} // namespace rsa 
} // namespace crypto 
} // namespace console 
} // namespace app 
} // namespace xos 

#endif // _XOS_APP_CONSOLE_CRYPTO_RSA_GENERATOR_MAINOPT_HPP 
